# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist

# Setup
title:            javmarina
tagline:          'Javier Marina Miranda'
description:      R&D Firmware Engineer @ HP. BSc. in Electronics, Robotics and Mechatronics Engineering.
url:              https://javmarina.github.io
baseurl:          /

# Google Analytics
google_analytics: G-7DD1B22849

author:
  name:           'Javier Marina'
  url:            https://www.linkedin.com/in/javmarina/

paginate:         5

github:
  repo:           https://github.com/javmarina/javmarina.github.io
